### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by ericmjl** [CamDavidsonPilon/autograd-gamma#9]
@CamDavidsonPilon I took the liberty of making a conda-forge package for autograd-gamma. I hope you don't mind. I needed it to build ngboost, which also makes use of autograd-gamma.

Just putting a heads-up for you.

**Comment by ericmjl** [comment]
I just  realized there's already a conda-forge recipe that has been merged, it's just that the package hasn't shown up on conda-forge. Closing this issue!

**Comment by CamDavidsonPilon** [comment]
❤️ thanks for putting the effort in @ericmjl!
